export let songUris = [
	{ artist: 'The Beatles', song: `Let It Be`, uri: '7iN1s7xHE4ifF5povM6A48' },
	{ artist: 'Queen', song: `Don't Stop Me Now`, uri: '7hQJA50XrCWABAu5v6QZ4i' },
	{ artist: 'Taylor Swift', song: `Cruel Summer`, uri: '1BxfuPKGuaTgP7aM0Bbdwr' },
	{ artist: 'ABBA', song: `Dancing Queen`, uri: '0GjEhVFGZW8afUYGChu3Rr' },
	{ artist: 'Adele', song: `Someone Like You`, uri: '1zwMYTA5nlNjZxYrvBB2pV' },
	{ artist: 'Fleetwood Mac', song: `Go Your Own Way`, uri: '4xh7W7tlNMIczFhupCPniY' },
	{ artist: 'Beyoncé', song: `Cuff It`, uri: '1xzi1Jcr7mEi9K2RfzLOqS' },
	{ artist: 'Led Zeppelin', song: `Stairway to Heaven`, uri: '5CQ30WqJwcep0pYcV4AMNc' },
	{ artist: 'Elton John', song: `Cold Heart - PNAU Remix`, uri: '7rglLriMNBPAyuJOMGwi39' },
	{ artist: 'Katy Perry', song: `The One That Got Away`, uri: '6GCW5Muk3u0cM5QTkS4C9a' },
	{ artist: 'Billy Joel', song: `Movin' Out (Anthony's Song)`, uri: '16GUMo6u3D2qo9a19AkYct' },
	{ artist: 'Michael Jackson', song: `Smooth Criminal`, uri: '2bCQHF9gdG5BNDVuEIEnNk' },
	{ artist: 'Eagles', song: `Hotel California`, uri: '40riOy7x9W7GXjyGp4pjAv' },
	{
		artist: 'U2',
		song: `I Still Haven't Found What I'm Looking For`,
		uri: '6wpGqhRvJGNNXwWlPmkMyO'
	},
	{ artist: 'Phil Collins', song: `You Can't Hurry Love`, uri: '4YwbSZaYeYja8Umyt222Qf' },
	{ artist: 'Celine Dion', song: `My Heart Will Go On`, uri: '33LC84JgLvK2KuW43MfaNq' },
	{ artist: 'Justin Bieber', song: `Baby`, uri: '6epn3r7S14KUqlReYr77hA' },
	{ artist: 'Metallica', song: `Enter Sandman`, uri: '3VqHuw0wFlIHcIPWkhIbdQ' },
	{ artist: 'Madonna', song: `Like a Prayer`, uri: '2v7ywbUzCgcVohHaKUcacV' },
	{ artist: 'Bon Jovi', song: `Livin' On A Prayer`, uri: '37ZJ0p5Jm13JPevGcx4SkF' },
	{ artist: 'Rihanna', song: `Don't Stop The Music`, uri: '1Jo0Zg7XlrA6z0mFTZVdkn' },
	{ artist: 'Red Hot Chili Peppers', song: `Can't Stop`, uri: '3ZOEytgrvLwQaqXreDs2Jx' },
	{
		artist: 'Whitney Houston',
		song: `I Wanna Dance With Somebody`,
		uri: '2tUBqZG2AbRi7Q0BIrVrEj2'
	},
	{
		artist: 'Garth Brooks',
		song: `I Don't Need Your Rockin' Chair`,
		uri: '3nKLfeoq3YedJIZqvRW3Qz'
	},
	{ artist: 'Maroon 5', song: `Sugar`, uri: '2iuZJX9X9P0GKaE93xcPjk' },
	{ artist: 'Lady Gaga', song: `Bad Romance`, uri: '0SiywuOBRcynK0uKGWdCnn' },
	{ artist: 'AC/DC', song: `Highway to Hell`, uri: '2zYzyRzz6pRmhPzyfMEC8s' },
	{ artist: 'Frank Sinatra', song: `Fly Me to The Moon`, uri: '5b7OgznPJJr1vHNYGyvxau' },
	{ artist: 'Jay-Z', song: `Empire State of Mind`, uri: '2igwFfvr1OAGX9SKDCPBwO' },
	{ artist: 'Eminem', song: `Without Me`, uri: '7lQ8MOhq6IN2w8EYcFNSUk' },
	{ artist: 'Aerosmith', song: `Dream On`, uri: '1xsYj84j7hUDDnTTerGWlH' },
	{ artist: 'Britney Spears', song: `Toxic`, uri: '6I9VzXrHxO9rA9A5euc8Ak' },
	{ artist: 'Lil Wayne', song: `Sucker for Pain`, uri: '4dASQiO1Eoo3RJvt74FtXB' },
	{ artist: 'Bruce Springsteen', song: `Dancing in the Dark`, uri: '7FwBtcecmlpc1sLySPXeGE' },
	{ artist: 'Elvis Presley', song: `Can't Help Falling In Love`, uri: '44AyOl4qVkzS48vBsbNXaC' },
	{ artist: 'Drake', song: `One Dance`, uri: '1zi7xx7UVEFkmKfv06H8x0' },
	{ artist: 'Bruno Mars', song: `Marry You`, uri: '22PMfvdz35fFKYnJyMn077' },
	{ artist: 'Bee Gees', song: `Stayin' Alive`, uri: '3mRM4NM8iO7UBqrSigCQFH' },
	{
		artist: 'Mariah Carey',
		song: `All I Want for Christmas Is You`,
		uri: '0bYg9bo50gSsH3LtXe2SQn'
	},
	{ artist: 'Ed Sheeran', song: `The A Team`, uri: '1VdZ0vKfR5jneCmWIUAMxK' },
	{ artist: 'Rolling Stones', song: `Start Me Up`, uri: '7HKez549fwJQDzx3zLjHKC' },
	{ artist: 'Kanye', song: `Flashing Lights`, uri: '5TRPicyLGbAF2LGBFbHGvO' },
	{ artist: 'Julio Iglesias', song: `Me Olvide De Vivire`, uri: '0kVOor973ijVqOBhYqvaE8' },
	{ artist: 'Chris Brown', song: `Forever`, uri: '3NZJlJemX3mzjf56MqC5ML' },
	{ artist: 'Barbra Streisand', song: `Woman in Love`, uri: '1pTGc8pwyo6xtgXBKCBcFn' }
];
